app/urls.py
from django.urls import path
from app import views
from django.conf import settings
from django.conf.urls.static import static
from .views import CustomerRegistrationView
from django.contrib.auth import views as auth_views
from .forms import LoginForm, MyPasswordChangeForm,SetPasswordForm
from django.contrib.auth.forms import PasswordResetForm
from django.contrib.auth import get_user_model
from .views import ProfileView
# from django.urls import path
from .views import orders











urlpatterns = [
    # path('', views.home),
path('', views.ProductView.as_view(), name="home"),  
path('product-detail/<int:pk>', views.ProductDetailView.as_view(), name='product-detail'), 
path('buy/', views.buy_now, name='buy-now'),


path('sendotp/', views.send_otp, name='sendotp'),
path('verify_otp/', views.verify_otp, name='verify_otp'),
   

path('add-to-cart/', views.add_to_cart, name='add-to-cart'),

path('cart/', views.show_cart, name='showcart'),


path('pluscart/', views.plus_cart),
path('minuscart/', views.minus_cart),

path('removecart/', views.remove_cart),



# app/urls.py



    # Other paths...
    path('orders/', orders, name='orders'),


path('profile/', ProfileView.as_view(), name='profile'),

path('address/', views.address, name='address'),
path('address/', views.address, name='address'),

path('mobile/', views.mobile, name='mobile'),
path('mobile/<slug:data>', views.mobile, name='mobile'),

path('laptop/', views.laptop, name='laptop'),
path('laptop/<slug:data>', views.laptop, name='laptop'),  

path('topwears/', views.topwears, name='topwears'),
path('topwears/<slug:data>', views.topwears, name='topwears'),

path('bottomwears/', views.bottomwears, name='bottomwears'),
path('bottomwears/<slug:data>', views.bottomwears, name='bottomwears'),

path('registration/', CustomerRegistrationView.as_view(), name='customerregistration'),

path('accounts/', auth_views.LoginView.as_view(template_name='app/login.html', authentication_form=LoginForm),name='login'),

path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),

path('password-reset/done/',auth_views.PasswordResetDoneView.as_view(template_name='app/password_reset_done.html'),name='password_reset_done'),

path('password-reset-confirm/<uidb64>/<token>/',auth_views.PasswordResetConfirmView.as_view(template_name='app/password_reset_confirm.html',form_class=SetPasswordForm),name='password_reset_confirm'),

path('password-reset-complete/',auth_views.PasswordResetCompleteView.as_view(template_name='app/password_reset_complete.html'), name='password_reset_complete'),

path('checkout/', views.checkout, name='checkout'),
path('paymentdone/', views.payment_done, name='paymentdone'),

path('password-reset/', auth_views.PasswordResetView.as_view(template_name='app/password_reset.html',form_class=PasswordResetForm),name='password_reset'),

path('passwordchange/', auth_views.PasswordChangeView.as_view(template_name='app/passwordchange.html',form_class=MyPasswordChangeForm, success_url='/pass/'),name='passwordchange'),
path('pass/', auth_views.PasswordChangeView.as_view(template_name='app/pass.html'),name='pass'),



] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shoppinglyx/urls.py
from django.contrib import admin
from django.urls import path, include



urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('app.urls')),
    

]

app/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator,MinValueValidator



# Create your models here.
STATE_CHOICES = (
    ('Andhra Pradesh','Andhra Pradesh'),
    ('Arunachal Pradesh','Arunachal Pradesh'),
    ('Assam','Assam'),
    ('Bihar','Bihar'), 
    ('Chhattisgarh','Chhattisgarh'), 
    ('Goa','Goa'), 
    ('Gujarat','Gujarat'), 
    ('Haryana','Haryana'), 
    ('Himachal Pradesh','Himachal Pradesh'), 
    ('Jharkhand','Jharkhand'), 
    ('Karnataka','Karnataka'), 
    ('Karnataka','Karnataka'),
    ('Madhya Pradesh','Madhya Pradesh'),
    ('Maharashtra','Maharashtra'),
    ('Manipur','Manipur'),
    ('Meghalaya','Meghalaya'),
    ('Mizoram','Mizoram'),
    ('Nagaland','Nagaland'),
    ('Odisha','Odisha'),
    ('Punjab','Punjab'),
    ('Rajasthan','Rajasthan'),
    ('Sikkim','Sikkim'),
    ('Tamil Nadu','Tamil Nadu'),
    ('Telangana','Telangana'),
    ('Tripura','Tripura'),
    ('Uttar Pradesh','Uttar Pradesh'),
    ('Uttarakhand','Uttarakhand'),
    ('West Bengal','West Bengal'),
)

class Customer(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    name = models.CharField(max_length=200)
    locality = models.CharField(max_length=200)
    city = models.CharField(max_length=50)
    zipcode = models.IntegerField()
    state = models.CharField(choices=STATE_CHOICES, max_length=50)


def __str__(self):
    return str(self.id)

CATEGORY_CHOICES = (
    ('M', 'Mobile'),
    ('L', 'Laptop'),
    ('TW', 'Top Wear'),
    ('BW', 'Bottom Wear'),
)

class Product(models.Model):
    title = models.CharField(max_length=200)
    selling_price= models.FloatField()
    discounted_price = models.FloatField()
    description = models.TextField()
    brand = models.CharField(max_length=100)
    category = models.CharField(choices=CATEGORY_CHOICES, max_length=2)
    product_image = models.ImageField(upload_to='productimg')

def __str__(self):
    return str(self.id)

# class Cart(models.Model):
#     user = models.ForeignKey(User, on_delete=models.CASCADE)
#     product = models.ForeignKey(Product, on_delete=models.CASCADE)
#     quantity = models.PositiveIntegerField(default=1)

# def __str__(self):
#     return str(self.id)

# @property
# def total_cost(self):
#     return self.quantity * self.product.discounted_price

class Cart(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)

    def __str__(self):
        return str(self.id)

    @property
    def total_cost(self):
        return self.quantity * self.product.discounted_price

STATUS_CHOICES = (
       ('Accepted','Accepted'),
       ('Packed','Packed'),
       ('On The Way','On The Way'),
       ('Delivered','Delivered'),
       ('Cancel','Cancel'),
    )

class OrderPlaced(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=1)
    ordered_date = models.DateTimeField(auto_now_add=True)
    status = models.CharField(max_length=50, choices=STATUS_CHOICES,default='panding')

    @property
    def total_cost(self):
        return self.quantity * self.product.discounted_price
    
    
class PasswordReset(models.Model):
	user=models.OneToOneField(User,on_delete=models.CASCADE)
	forget_password_token=models.CharField(max_length=100)
	created_at=models.DateTimeField(auto_now_add=True)



class OTP(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    otp_secret = models.CharField(max_length=16)
    email = models.EmailField(unique=True)
    is_verified = models.BooleanField(default=False)

    def __str__(self):
        return self.email

from django.contrib import admin
admin.site.register(OTP)

app/templates/app/addtocart.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Cart{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <h1 class="text-center mb-5">Shopping Cart</h1>
  <div class="col-sm-8">
  <div class="card">
   <div class="card-body">
    <h3>Cart</h3>
    {% for cart in carts %}
    <hr>
    <div class="row">
     <div class="col-sm-3 text-center align-self-center"><img src="{{cart.product.product_image.url}}" alt="" srcset="" class="img-fluid img-thumbnail shadow-sm" height="150" width="150"> </div>
     <div class="col-sm-9">
      <div>
       <h5>{{cart.product.title}}</h5>
       <p class="mb-2 text-muted small">{{cart.product.description}}</p>
       <div class="my-3">
        <label for="quantity">Quantity:</label>
        <a class="minus-cart btn" pid="{{cart.product.id}}"><i class="fas fa-minus-square fa-lg"></i></a>
          <span id="quantity">{{cart.quantity}}</span>
        <a class="plus-cart btn" pid="{{cart.product.id}}"><i class="fas fa-plus-square fa-lg"></i></a>
       </div> 
       <div class="d-flex justify-content-between">
        <a href="#" class="btn btn-sm btn-secondary mr-3 remove-cart" pid="{{cart.product.id}}">Remove item </a>
        <p class="mb-0"><span><strong>Rs. {{cart.product.discounted_price}}</strong></span></p>
       </div>
      </div>
     </div>
    </div>
    {% endfor %}
    </div>
   </div>
  </div>
  <div class="col-sm-4">
   <div class="card">
    <div class="card-body">
      <h3>The Total Amount of</h3>
      <ul class="list-group">
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 pb-0">Amount<span>Rs. <span id="amount"> {{amount}}</span></span></li>
       <li class="list-group-item d-flex justify-content-between align-items-center px-0">Shipping<span>Rs. 70.00</span></li>
       <li class="list-group-item d-flex justify-content-between align-items-center border-0 px-0 mb-3">
        <div>
           <strong>Total</strong> <small>(including VAT)</small>
         </div>
         <span><strong>Rs.<strong id="totalamount"> {{totalamount}}</strong>  </strong></span>
       </li>
      </ul>
      <div class="d-grid"><a href="{% url 'checkout' %}" class="btn btn-primary">Place Order</a></div>
    </div>
   </div>
  </div>
  
 </div>
</div>
<div class="container">
 <div class="row">
  <div class="col-sm-8">
   <div class="card">
    <div class="card-body">
      <h5 class="mb-4">We accept</h5>
      <img src="{% static 'app/images/payment.png' %}" alt="" class="img-fluid">
    </div>
  </div>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/base.html
<!doctype html>
{% load static %}
<html lang="en">
  <head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <!-- Bootstrap CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
   
    <!--Owl Carousel CSS-->
    <link rel="stylesheet" href="{% static 'app/css/owl.carousel.min.css' %}">
  

    <!--FontAwesome CSS-->
    <link rel="stylesheet" href="{% static 'app/css/all.min.css' %}">

    <!--Custom CSS-->
    <link rel="stylesheet" href="{% static 'app/css/style.css' %}">


    <title>ShoppingX | {% block title %} {% endblock title %} </title>
  </head>
  <body>

    <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
     <div class="container">
       <a class="navbar-brand" href="/"><font size="10" color="grey"> <b>UVJ </b> </font> </a>
       <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
         <span class="navbar-toggler-icon"></span>
       </button>
       <div class="collapse navbar-collapse" id="navbarSupportedContent">
         <ul class="navbar-nav me-auto mb-2 mb-lg-0">
           <li class="nav-item">
             <a class="nav-link active" aria-current="page" href="/">Home</a>
           </li>
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle text-white" href="#" id="electronicsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               Electronics
             </a>
             <ul class="dropdown-menu" aria-labelledby="electronicsDropdown">
               <li><a class="dropdown-item" href="{% url 'mobile' %}">Mobile</a></li>
               <li><a class="dropdown-item" href="{% url 'laptop' %}">Laptop</a></li>
             </ul>
           </li>
           <li class="nav-item dropdown">
             <a class="nav-link dropdown-toggle text-white" href="#" id="fashionDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
               Fashion
             </a>
             <ul class="dropdown-menu" aria-labelledby="fashionDropdown">
               <li><a class="dropdown-item" href="{% url 'topwears' %}">Top Wear</a></li>
               <li><a class="dropdown-item" href="{% url 'bottomwears' %}">Bottom Wear</a></li>
             </ul>
           </li>
         </ul>
         <form class="d-flex">
           <input class="form-control me-2" type="search" placeholder="Search" aria-label="Search">
           <button class="btn btn-warning" type="submit"> {{request.user.username|capfirst}}
             
          </button>
         </form>
         <div>
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            {% if request.user.is_authenticated %}
           <li class="nav-item dropdown mx-2">
              <a class="nav-link dropdown-toggle text-white" href="#" id="profileDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
              {{request.user.username|capfirst}}
              </a>
              <ul class="dropdown-menu" aria-labelledby="profileDropdown">
                <li><a class="dropdown-item" href="{% url 'profile' %}">Profile</a></li> 
                <li><a class="dropdown-item" href="{% url 'orders' %}">Orders</a></li>
                <li><a class="dropdown-item" href="{% url 'passwordchange' %}">Change Password</a></li>
                <li><a class="dropdown-item" href="{% url 'logout' %}">Logout</a></li>
              </ul>
            </li>
            <li class="nav-item mx-2">
             <a href="{% url 'showcart' %}" class="nav-link text-white"><span class="badge bg-danger"><ul>
              <!-- base.html -->
<div id="cart-counter">
  {% if request.user.is_authenticated %}
      {% with request.user.cart_set.count as cart_count %}
          Cart: {{ cart_count }}
      {% endwith %}
  {% endif %}
</div>
            </span>  </a>
            </li>
            {% else %}

            
            
              <li class="nav-item mx-2">
             
            {% comment %} <a href="{% url 'login' %}" class="nav-link text-white">Login</a> {% endcomment %}
            <p><a href="{% url 'sendotp' %}" class="nav-link text-white">Login</a></p>

            </li>
            <li class="nav-item mx-2">
             <a href="{% url 'customerregistration' %}" class="nav-link text-white">Registration</a>
            </li>
            {% endif %}
          </ul>
         </div>
       </div>
     </div>
    </nav>
    {% block banner_slider %} {% endblock banner_slider %}
    {% block livesale %} {% endblock livesale %}
    {% block main-content %} {% endblock main-content %}
    {% block payment-gatway %} {% endblock payment-gatway %}

<br>
<br>
<br>
<br>

<br>
<br>
<br>
    <!-- Start Footer -->
    <title>Footer Design</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/css/all.min.css">
  
    <style>
        @import url("https://fonts.googleapis.com/css2?family=Poppins:wght@300;400;500;600;700&display=swap");
        body {
            line-height: 1.5;
            font-family: "Poppins", sans-serif;
        }
        
        * {
            margin: 0;
            padding: 0;
            box-sizing: border-box;
        }
        
        .container {
            max-width: 1170px;
            margin: auto;
        }
        
        .row {
            display: flex;
            flex-wrap: wrap;
        }
        
        ul {
            list-style: none;
        }
        
        .footer {
            background-color: #24262b;
            padding: 70px 0;
        }
        
        .footer-col {
            width: 25%;
            padding: 0 15px;
        }
        
        .footer-col h4 {
            font-size: 18px;
            color: #ffffff;
            text-transform: capitalize;
            margin-bottom: 35px;
            font-weight: 500;
            position: relative;
        }
        
        .footer-col h4::before {
            content: "";
            position: absolute;
            left: 0;
            bottom: -10px;
            background-color: #e91e63;
            height: 2px;
            box-sizing: border-box;
            width: 50px;
        }
        
        .footer-col ul li:not(:last-child) {
            margin-bottom: 10px;
        }
        
        .footer-col ul li a {
            font-size: 16px;
            text-transform: capitalize;
            color: #ffffff;
            text-decoration: none;
            font-weight: 300;
            color: #bbbbbb;
            display: block;
            transition: all 0.3s ease;
        }
        
        .footer-col ul li a:hover {
            color: #ffffff;
            padding-left: 8px;
        }
        
        .footer-col .social-links a {
            display: inline-block;
            height: 40px;
            width: 40px;
            background-color: rgba(255, 255, 255, 0.2);
            margin: 0 10px 10px 0;
            text-align: center;
            line-height: 40px;
            border-radius: 50%;
            color: #ffffff;
            transition: all 0.5s ease;
        }
        
        .footer-col .social-links a:hover {
            color: #24262b;
            background-color: #ffffff;
        }
        /*responsive*/
        
        @media (max-width: 767px) {
            .footer-col {
                width: 50%;
                margin-bottom: 30px;
            }
        }
        
        @media (max-width: 574px) {
            .footer-col {
                width: 100%;
            }
        }
    </style>
    
    <body>
    
        <footer class="footer">
            <div class="container">
                <div class="row">
                    <div class="footer-col ">
                        <h4>UVJ</h4>
                        <ul>
                            <li><a href="#"><font color="white"> Home </font></a></li>
                            <li class="nav-item dropdown">
                              <a class="nav-link dropdown-toggle text-white" href="#" id="electronicsDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                Electronics
                              </a>
                              <ul class="dropdown-menu" aria-labelledby="electronicsDropdown">
                                <li><a class="dropdown-item" href="{% url 'mobile' %}"> <font  color="black">Mobile </font></a></li>
                                <li><a class="dropdown-item" href="{% url 'laptop' %}"> <font color="black"> Laptop </font></a></li>
                              </ul>
                              <li class="nav-item dropdown">
                                <a class="nav-link dropdown-toggle text-white" href="#" id="fashionDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                                  Fashion
                                </a>
                                <ul class="dropdown-menu" aria-labelledby="fashionDropdown">
                                  <li><a class="dropdown-item" href="{% url 'topwears' %}"><font color="black"> Top Wear </font></a></li>
                                  <li><a class="dropdown-item" href="{% url 'bottomwears' %}"><font color="black">Bottom Wear </font></a></li>
                                </ul>
                              </li>
                            </ul>
                    </div>
                    <div class="footer-col">
                        <h4>get help</h4>
                        <ul>
                            <li><a href="#">FAQ</a></li>
                            <li><a href="#">shipping</a></li>
                            <li><a href="#">returns</a></li>
                            <li><a href="#">order status</a></li>
                            <li><a href="#">payment options</a></li>
                        </ul>
                    </div>
                    <div class="footer-col">
                        <h4>online shop</h4>
                        <ul>
                            <li><a href="#">watch</a></li>
                            <li><a href="#">bag</a></li>
                            <li><a href="#">shoes</a></li>
                            <li><a href="#">dress</a></li>
                        </ul>
                    </div>
                    <div class="footer-col">
                        <h4>follow us</h4>
                        <div class="social-links">
                            <a href="#"><i class="fab fa-facebook-f"></i></a>
                            <a href="#"><i class="fab fa-twitter"></i></a>
                            <a href="https://www.instagram.com/vipulsinh_mori_?igsh=OGQ5ZDc2ODk2ZA=="><i class="fab fa-instagram"></i></a>
                            <a href="#"><i class="fab fa-linkedin-in"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </footer>
    

     <!-- End Footer -->

    <!-- Jquery -->
    <script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
    <!-- Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.bundle.min.js" integrity="sha384-ygbV9kiqUc6oa4msXn9868pTtWMgiQaeYH7/t7LECLbyPA2x65Kgf80OJFdroafW" crossorigin="anonymous"></script>

    <script src="{% static 'app/js/owl.carousel.min.js' %}"></script>
    <script src="{% static 'app/js/all.min.js' %}"></script>
    <script src="{% static 'app/js/myscript.js' %}"></script>
  </body>
</html>

app/templates/app/buynow.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
Product Buy Now
{% endblock main-content %}

app/templates/app/emtycart.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %} Emty Cart  {% endblock %}
{% block main-content %}
<div class="container my-5">
    <div class="row">
        <h3 class="text-center"> You Have No Product In Your </h3>
        <div class="text-center">
            <img src="{% static 'app\images\images.png' %}" alt="" class="img-fluid img-thumbnail w-25">
        </div>
    </div>
</div>
{% endblock main-content %}

app/templates/app/googlepay.html
<!-- payment/googlepay.html -->
<!DOCTYPE html>
<html>
<head>
    <title>Google Pay Integration</title>
</head>
<body>
    <!-- Your content -->
    <div id="google-pay-button">GooglePay</div>

    <script src="https://pay.google.com/gp/p/js/pay.js"></script>
    <script>
        googlePayClient =
            new google.payments.api.PaymentsClient({environment: 'TEST'});
        const button =
            googlePayClient.createButton({onClick: handleGooglePayPayment});
        document.getElementById('google-pay-button').appendChild(button);

        function handleGooglePayPayment() {
            // Implement Google Pay payment flow
            // Retrieve payment data and send it to your Django server
            // Handle the server's response accordingly
        }
    </script>
</body>
</html>

app/templates/app/laptop.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <div class="col-sm-3">
    <div class="list-group">
        <a href="{% url 'laptop' %}" class="list-group-item list-group-item-action" aria-current="true">All laptop </a>
        <a href="{% url 'laptop' 'lenevo' %}" class="list-group-item list-group-item-action" aria-current="true">Lenevo </a>
        <a href="{% url 'laptop' 'Asus' %}" class="list-group-item list-group-item-action" aria-current="true">Asus </a>
        <a href="{% url 'laptop' 'below' %}" class="list-group-item
        list-group-item-action" aria-current="true">Below 10000 </a>
        <a href="{% url 'laptop' 'above' %}" class="list-group-item
        list-group-item-action" aria-current="true">above 10000 </a>
        

    </div>
  </div>
  
  <div class="col-sm-8 offset-sm-1">
    <div class="row">
    {% for product in laptop %}
    <div class="col-4 text-center mb-4">
        <a href="{% url 'product-detail' product.id %}" class="btn">
            <div class="item">
                <img src="{{product.product_image.url}}" alt="" height="300" class="">
                <div class="fw-bold">{{product.title}}</div>
                <div class="fw-bold">Rs.{{product.discounted_price}} 
                    <small class="fw-light text-decoration-line-through">{{product.selling_price}}</small></div>
            </div>
        </a>
    </div>
    {% endfor %}
  </div>
 </div>
</div>
</div>
{% endblock main-content %}

app/templates/app/login.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Login{% endblock title %}
{% block main-content %}
<div class="container">
 <div class="row my-3">
  <div class="col-sm-6 offset-sm-3">
   <h3>Login</h3>
   <hr>
   <form action="" method="post" novalidate class="shadow p-5">
    {% csrf_token %}
    {% for fm in form %}
    <div class="form-group">
        {{fm.label_tag}} {{fm}} <small class="text-danger">{{fm.error|striptags}}</small><br>
    </div>
    {% endfor %}
     <small><a href="{% url 'password_reset' %}">Forgotpassword ? </a></small>
    <br> 
    <input type="submit" class="btn btn-primary mt-4" value="Login">
    <br>
    <div class="text-center text-primary fw-bold"><small>New to ShoppinglyX ? <a href="{% url 'customerregistration' %}" class="text-danger"> Create an Account</a></small></div>
    {% if form.non_field_error %}
    {% for error in form.non_field_errors %}
    <p class="text-danger alert-danger my-3"> {{error}}</p>
    {% endfor %}
    {% endif%}
     </form>
  </div>
 </div>
</div>
{% endblock main-content %}

app/templates/app/mobile.html
{% extends 'app/base.html' %}
{% load static %}
{% block title %}Buy Now{% endblock title %}
{% block main-content %}
<div class="container my-5">
 <div class="row">
  <div class="col-sm-3">
    <div class="list-group">
        <a href="{% url 'mobile' %}" class="list-group-item list-group-item-action" aria-current="true">All Mobile </a>
        <a href="{% url 'mobile' 'oneplus' %}" class="list-group-item list-group-item-action" aria-current="true">Oneplus </a>
        <a href="{% url 'mobile' 'Vivo' %}" class="list-group-item list-group-item-action" aria-current="true">Vivo </a>
        <a href="{% url 'mobile' 'below' %}" class="list-group-item
        list-group-item-action" aria-current="true">Below 10000 </a>
        <a href="{% url 'mobile' 'above' %}" class="list-group-item
        list-group-item-action" aria-current="true">above 10000 </a>
        

    </div>
  </div>
  
  <div class="col-sm-8 offset-sm-1">
    <div class="row">
    {% for product in mobile %}
    <div class="col-4 text-center mb-4">
        <a href="{% url 'product-detail' product.id %}" class="btn">
            <div class="item">
                <img src="{{product.product_image.url}}" alt="" height="300" class="">
                <div class="fw-bold">{{product.title}}</div>
                <div class="fw-bold">Rs.{{product.discounted_price}} 
                    <small class="fw-light text-decoration-line-through">{{product.selling_price}}</small></div>
            </div>
        </a>
    </div>
    {% endfor %}
  </div>
 </div>
</div>
</div>
{% endblock main-content %}